# Generated by Django 4.0.4 on 2022-05-24 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishlatilgan',
            fields=[
                ('kod', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('summa', models.PositiveIntegerField(default=0)),
                ('user_id', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kashlar',
            fields=[
                ('kod', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('summa', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
