# Generated by Django 4.0.4 on 2022-05-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_ishlatilgan_kashlar_remove_order_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('summa', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
