# Generated by Django 4.0.4 on 2022-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_doctorpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpay',
            name='name',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
